[package]
name = "mysql_binlog_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
sha1_smol = "1.0.0"
num = "0.4.0"
encoding = "0.2.33"
bigdecimal = "0.1.0"
bit-set = "0.4.0"